# Auto-generated from katrain/i18n/locales/en/LC_MESSAGES/katrain.po
# v2: single-language UI (English)

STRINGS_EN: dict[str, str] = {
    "": "",
    "All binaries downloaded": "All available binaries already downloaded",
    "All models downloaded": "All available models already downloaded",
    "Analyzing move...": "Analyzing move...",
    "Copied SGF to clipboard.": "Copied SGF to clipboard.",
    "Delete Node": "Delete Node",
    "Endgame": "Endgame",
    "Engine died unexpectedly": "Engine died unexpectedly without sending output: {error}",
    "Engine missing DLL": "Failed to start KataGo due to missing DLL. Check the requirements in the KataGo documentation, or try running the binary by itself for details. ",
    "Entire Game": "Entire Game",
    "Failed to import from clipboard": "Failed to import game from clipboard: {error}\nClipboard contents: {contents}...",
    "Failed to load SGF": "Failed to load SGF: {error}",
    "Filename": "Filename",
    "Info:AI thoughts": "AI thought process: {thoughts}",
    "Info:PV": "PV: {pv}",
    "Info:best move": "Move was predicted best move",
    "Info:point loss": "Estimated point loss: {points_lost:.1f}",
    "Info:policy best": "Top policy move was {move} ({probability:.1%}).",
    "Info:policy rank": "Move was #{rank} according to policy  ({probability:.2%}).",
    "Info:score": "Score: {score}",
    "Info:teaching undo": "Move was automatically undone in teaching mode.",
    "Info:top move": "Predicted top move was {top_move} ({score}).",
    "Info:undo predicted PV": "Predicted follow-up: {pv}",
    "Info:winrate": "Win rate: {winrate}",
    "Jigo": "Jigo",
    "Kata config not found": "KataGo config file {config} does not exist, please check general settings.",
    "Kata exe not found": "KataGo binary {exe} does not exist, please check general settings.",
    "Kata exe not found in path": "KataGo binary '{exe}' not found in your PATH, check your environment variables or use the full path in general settings instead. If on MacOS, see the manual on how to use brew to install katago first",
    "Kata model not found": "KataGo model {model} does not exist, please check general settings.",
    "Load File": "Load File",
    "Make Main Branch": "Make Main Branch",
    "Midgame": "Midgame",
    "New Game title": "Set up New Game / Edit Game Info and Rules",
    "No analysis available": "No analysis available",
    "Opening": "Opening",
    "Prune Branch": "Prune Branch",
    "SGF Notes Hint": "Your SGF notes for this position here.",
    "SGF start message": "Moves marked 'X' indicate the top move according to KataGo, those with a square are moves that lose less than 0.5 points",
    "Save File": "Save File",
    "Select AI": "Select AI strategy to configure",
    "Starting Kata failed": "Starting KataGo with command '{command}' failed with error {error}.",
    "Toggle Collapse Branch": "Expand/Collapse",
    "aga": "AGA",
    "ai settings": "Advanced AI Settings",
    "ai-ponder": "This simply indicates the Engine status, going from green (idle) to orange (processing queries). It turns red when the engine has crashed or fails to start.",
    "ai:antimirror": "KataAntiMirror",
    "ai:default": "KataGo",
    "ai:handicap": "KataHandicap",
    "ai:human": "Human-like",
    "ai:jigo": "KataJigo",
    "ai:p:influence": "Influential Style",
    "ai:p:local": "Local Style",
    "ai:p:pick": "Blinded Policy",
    "ai:p:rank": "Calibrated Rank",
    "ai:p:tenuki": "Tenuki Style",
    "ai:p:territory": "Territorial Style",
    "ai:p:weighted": "Policy Weighted",
    "ai:policy": "Policy",
    "ai:pro": "Historical Pro",
    "ai:scoreloss": "Score Loss",
    "ai:simple": "Simple Style",
    "aihelp:antimirror": "Anti Mirror-go Mode of KataGo.",
    "aihelp:default": "Full strength KataGo AI. Strength is affected by 'max visits' and 'model' in the general settings 'engine' section and engine configuration file. No options are available here.",
    "aihelp:handicap": "KataGo optimized for playing higher handicap games.The 'pda' setting corresponds to 'playoutDoublingAdvantage' in KataGo, from black's perspective. When 'automatic' is set, KaTrain will find a suitable value automatically.",
    "aihelp:human": "Picks moves according to a human-like KataGo model. If 'modern_style' is ticked, the model will play according to a post-2016 AlphaZero opening style.",
    "aihelp:jigo": "Will try to win by a set amount of points (default 0.5), without further restrictions.",
    "aihelp:p:influence": "Picks moves biased above the 'threshold' line and plays the best one. Increase 'line_weight' to penalize moves near the edge more. Stops strategy after the 'endgame' fraction of the board is filled.",
    "aihelp:p:local": "Picks 'pick_n + pick_frac * <number of legal moves>' weighted towards the last move and plays the best one. Plays top move if policy value is above 'pick_override' to avoid obvious mistakes.",
    "aihelp:p:pick": "Picks 'pick_n + pick_frac * <number of legal moves>' at random and plays the best one. For 'pick_frac=1' plays like the 'Policy' AI. Plays top move if policy value is above 'pick_override' to avoid obvious mistakes.",
    "aihelp:p:rank": "Picks a limited number of legal moves at random and plays the best one. Stronger settings select the best move from a larger selection. Since there is no 0 kyu/dan, 3 dan = -2 kyu.",
    "aihelp:p:tenuki": "Picks 'pick_n + pick_frac * <number of legal moves>' weighted away from the last move and plays the best one. Plays top move if policy value is above 'pick_override' to avoid obvious mistakes. A higher 'stddev' makes it play further away.",
    "aihelp:p:territory": "Picks moves biased below the 'threshold' line and plays the best one. Increase 'line_weight' to penalize moves near the center more. Stops strategy after the 'endgame' fraction of the board is filled.",
    "aihelp:p:weighted": "Plays moves according to policy probability, with 'weaken_fac' influencing how much more likely weaker moves are played. With a very low value it plays like the 'Policy' AI. 'pick_override' determines when top move is chosen without randomness, and 'lower_bound' determines the lower bound policy value that is allowed.",
    "aihelp:policy": "Plays the top move from the policy network, without any reading. Strength is mainly affected by 'model' in engine settings. The 'opening_moves' setting affects how many moves in the opening are more random.",
    "aihelp:pro": "Picks moves according to a human-like KataGo model. Specifically, Imitate pro and strong insei moves based on historical game records from the specified year and surrounding years.",
    "aihelp:scoreloss": "Plays moves that lead to more points lost with lower probability. Likely to play more varied/weaker with higher visits settings.",
    "aihelp:simple": "Plays moves that lead to simplifying the board state. Of moves that lose at most 'max_points_lost' points and with at least 'min_visits', prefer moves that lose fewer points, settle own territory more (with importance settled_weight), settle opponent's territory more (importance settled_weight * opponent_fac), avoid tenuki (more than 5 spaces, importance tenuki_penalty), and avoid attachments (importance attachment_penalty). Weights can be negative to make it complicate the game instead, and wide root noise (in general settings) can be used to play more according to the style at the cost of strength. ",
    "aistrategy": "AI Strategy",
    "analysis:aimove": "Force AI Move",
    "analysis:continuous": "Toggle continuous analysis",
    "analysis:dots": "Show\nDots",
    "analysis:nextmoves": "Next\nMoves",
    "analysis:playtoend": "Fast playout to game end",
    "analysis:policy": "Policy\nMoves",
    "analysis:reset": "Reset analysis",
    "analysis:territory": "Expected\nTerritory",
    "analysis:topmoves": "Top\nMoves",
    "avoids replaying": "Avoids replaying\nidentical games",
    "black player name hint": "Black player's name",
    "board size": "Board size",
    "board-game-end": "game\nend",
    "board-pass": "pass",
    "btn:Analysis": "Review",
    "btn:Analyze": "Analysis Options",
    "btn:Play": "Play",
    "cache analysis to sgf": "Cache analysis in SGF",
    "change engine suggestion": "First, try downloading KataGo versions and try if changing to a different executable helps in {link} .",
    "chinese": "Chinese",
    "clear cache": "Clear cache",
    "closedlabel:info&notes": "Move Info & Notes",
    "closedlabel:movestats": "Move Stats",
    "closedlabel:scoregraph": "Score Graph",
    "config file path": "All options are saved in:",
    "count down sound": "Sound on",
    "default katago option": "Detect platform and use provided OpenCL KataGo binary",
    "dot color": "Colour",
    "download katago button": "Download KataGo versions",
    "download models button": "Download Models",
    "editgame": "Edit Game Info",
    "engine died popup opening message": "The KataGo Engine failed to start, or crashed.\n\nThe error was: [color=#CC2222]{error_message}[/color]\n\nThe error code was: [color=#CC2222]{code}[/color].",
    "engine recovery": "Help with KataGo setup",
    "engine settings": "Engine Settings",
    "engine:altcommand": "Override Engine Command",
    "engine:altcommand:hint": "Full command used to start the engine. All other model options will be ignored.",
    "engine:config": "Path to KataGo config file",
    "engine:fast_visits": "Maximum number of visits in fast analysis",
    "engine:humanlike_model": "Path to human-like model",
    "engine:katago": "Path to KataGo executable",
    "engine:katago:hint": "Leave blank to use included executable",
    "engine:max_time": "Maximum time for analysis",
    "engine:max_visits": "Maximum number of visits in analysis",
    "engine:model": "Path to KataGo model",
    "engine:time:hint": "Time in seconds",
    "engine:wide_root_noise": "Wide root noise (increases variety of moves considered)",
    "engine:wide_root_noise:hint": "Use 0.02-0.1",
    "estimated strength": "Estimated Strength",
    "file not found": "Path does not exist",
    "from move": "from move",
    "game:normal": "Normal Game",
    "game:teach": "Teaching Game",
    "gametype": "Game Type",
    "general settings": "General Settings",
    "general settings title": "General and Engine Settings",
    "general:anim_pv_time": "Time between moves when animating a sequence",
    "general:debug_level": "Debug level in the console",
    "general:debug_level:hint": "Set to 1 when reporting errors",
    "go to engine help page": "If you are still having difficulties, {link} for an up-to-date troubleshooting page.",
    "gui-locked": "Action {action} not allowed in distributed self-play training mode. Restart KaTrain to exit this mode.",
    "handicap": "Handicap",
    "header:keystats": "Key Statistics",
    "header:num moves": "# Moves",
    "japanese": "Japanese",
    "katago binaries available": "{num} available katago versions found",
    "katago settings": "KataGo settings",
    "komi": "Komi",
    "korean": "Korean",
    "limit to moves": "Limit to moves",
    "link_here": "click here",
    "load sgf fast analysis": "Use fast analysis",
    "load sgf rewind": "Rewind to start",
    "load sgf title": "Load SGF File to Analyze",
    "local analysis": "Searching for local responses",
    "main time": "Main time (min.)",
    "menu:aisettings": "AI Settings",
    "menu:distributed": "Distributed Self-play Training",
    "menu:lang": "Language",
    "menu:load": "Load Game",
    "menu:manual": "Manual",
    "menu:newgame": "New Game/Change Rules",
    "menu:playersetup": "Player Setup",
    "menu:save": "Save Game",
    "menu:save-as": "Save Game As...",
    "menu:settings": "General & Engine Settings",
    "menu:support": "Contribute",
    "menu:teachsettings": "Teaching/Analysis Settings",
    "models available": "{num} available model(s) found",
    "move": "Move {number}",
    "move too fast": "Think for at least {num} seconds before playing.",
    "new zealand": "New Zealand",
    "newgame": "Start New Game",
    "non square board hint": "Use x:y (e.g. 19:9) for non-square size",
    "num undos": "Number of undos\n(teaching games)",
    "pass-button-text": "Pass",
    "player names": "Player Names",
    "player:ai": "AI",
    "player:human": "Human",
    "player:type": "Player",
    "point loss threshold": "Point loss greater than",
    "resign": "Resign",
    "restarting engine": "Restarting Engine after Settings Change.",
    "ruleset": "Rules",
    "save dots": "Save in SGF",
    "save sgf title": "Save SGF File",
    "sgf written": "SGF with analysis written to {file_name}",
    "short color B": "B",
    "short color W": "W",
    "show ai dots": "Show dots for AI players",
    "show dots": "Show dots",
    "show last n dots": "Show dots for the last <this many> moves",
    "show stats if": "Show stats if more than ... visits",
    "show two digits for point loss near zero": "Show two digits for point loss near zero",
    "stat:accuracy": "Accuracy Rating",
    "stat:aitop5": "AI Top 5 Match %",
    "stat:aitopmove": "AI Best Move Match %",
    "stat:meanpointloss": "Mean Point Loss",
    "stats:pointsgained": "Points Gained",
    "stats:pointslost": "Points Lost",
    "stats:score": "Estimated Score",
    "stats:winrate": "Win Rate",
    "stone_scoring": "Ancient Chinese",
    "strength:dan": "d",
    "strength:kyu": "k",
    "tab:info": "Info",
    "tab:info-details": "Details",
    "tab:notes": "Notes",
    "tab:points": "Point Loss",
    "tab:rank_est": "Rank Estimate",
    "tab:score": "Score",
    "tab:winrate": "Win Rate",
    "teacher settings": "Edit Teaching/Analysis Settings",
    "teaching undo message": "Undid move {move} as it lost {points_lost:.1f} points. Please try again. For a hint, hover over the move to see expected refutation, or check expected territory (t) to see the areas of the board where point loss is expected.",
    "theme": "Colour Theme",
    "theme:normal": "Default Theme",
    "theme:red-green-colourblind": "Red-Green Colourblind",
    "to move": "to move",
    "top_move_delta_score": "Change in score",
    "top_move_delta_winrate": "Change in win rate",
    "top_move_nothing": "(nothing)",
    "top_move_score": "Score",
    "top_move_visits": "Visits",
    "top_move_winrate": "Win rate",
    "tromp-taylor": "Tromp-Taylor",
    "undo-button-text": "Undo",
    "update ai settings": "Update AI Settings",
    "update settings": "Update Settings",
    "update teacher": "Update Feedback Settings",
    "wait-before-extra-analysis": "Wait for initial analysis to complete before requesting a refinement.",
    "white player name hint": "White player's name"
}
