name: release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip3 install poetry
        poetry install --with dev,test

    - name: Run tests
      run: pytest -v -s tests

    - name: Run I18N conversion
      run: python i18n.py

    - name: Build
      run: |
        poetry build

    - name: Release to PyPI
      env:
        POETRY_HTTP_BASIC_KATRAIN_USERNAME: ${{ secrets.PYPI_USER }}
        POETRY_HTTP_BASIC_KATRAIN_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: poetry publish --verbose
