name: release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.8"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        uv sync --group dev,test

    - name: Run tests
      run: uv run pytest -v -s tests

    - name: Run I18N conversion
      run: uv run python i18n.py

    - name: Build
      run: |
        uv build

    - name: Release to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: uv publish --verbose
