name: release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip3 install poetry
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry install --with dev,test

    - name: Run tests
      run: poetry run pytest -v -s tests

    - name: Run I18N conversion
      run: poetry run python i18n.py

    - name: Build
      run: |
        poetry build

    - name: Release to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --verbose
